version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
    

  pre_build:
    commnads:
      - yarn install
  
  build:
    commands:
      - yarn build

artifacts:
  files:
    - package.json
    - package-lock.json
    - .eslintrc.json
  base-directory: 'dist'